### PR TITLE
[LC-138] Embed `merkletools`

### PR DESCRIPTION
**Pull request by zsaladin**
## Embed [merkletools](https://github.com/Tierion/pymerkletools)
- To modify codes embed `merkletools`

### CODE REVIEW

**Comment by zsaladin** [comment]
#92 LC-143 must be merged before merging it.

**Comment by zsaladin** [comment]
retest this please

**Comment by zsaladin** [comment]
retest this please

**Comment by zsaladin** [comment]
retest this please

**Comment by zsaladin** [comment]
retest this please

**Comment by zsaladin** [comment]
retest this please

**Comment by zsaladin** [comment]
retest this please

**Review by hangaroy — APPROVED** [review]

**Review by hyerim-kim — APPROVED** [review]

**Review by windies21 — APPROVED** [review]

**Review by yakkle — APPROVED** [review]
👍

**Review by laurenceyoon — APPROVED** [review]

**Pull request merged**
