### PR TITLE
Add ICON badge

### PR DESCRIPTION
**Pull request by JINWOO-J**
Added an ICON badge in README.md

### CODE REVIEW

**Comment by yakkle** [comment]
Can one of the admins verify this patch?

**Comment by JINWOO-J** [comment]
> Can one of the admins verify this patch?

I hope @windies21 dose it.

**Comment by metalg0su** [comment]
Description please.

**Comment by JINWOO-J** [comment]
> Description please.
I did it

**Comment by JINWOO-J** [comment]
Fix it again in the develop branch
https://github.com/icon-project/loopchain/pull/451

**Pull request closed without merging**
