### PR TITLE
resolve conflict to merge to master

### PR DESCRIPTION
**Pull request by yakkle**
added commits
- LC-690 : update recommended python version
- update readme for 2.4.14

### CODE REVIEW

**Comment by yakkle** [comment]
retest this please

**Comment by yakkle** [comment]
retest this please

**Comment by yakkle** [comment]
retest this please

**Review by metalg0su — APPROVED** [review]

**Review by hyerim-kim — APPROVED** [review]

**Comment by yakkle** [comment]
retest this please

**Review by laurenceyoon — APPROVED** [review]

**Pull request merged**
